// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyiqvpudqowixwakxqis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5aXF2cHVkcW93aXh3YWt4cWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTc0MzUsImV4cCI6MjA4ODU5MzQzNX0.SVMtdSfQ0xD7MCz-Gqm-KXHl9IuU28-8xqvbPIFPR-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const safeStorage = {
  getItem: (key: string) => {
    try {
      return globalThis.localStorage?.getItem(key) ?? null;
    } catch (error) {
      console.error('Failed to read from localStorage:', error);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      globalThis.localStorage?.setItem(key, value);
    } catch (error) {
      console.error('Failed to write to localStorage:', error);
    }
  },
  removeItem: (key: string) => {
    try {
      globalThis.localStorage?.removeItem(key);
    } catch (error) {
      console.error('Failed to remove from localStorage:', error);
    }
  },
};

// Force clear any cached Supabase auth tokens that might cause 401 Unauthorized errors
if (typeof globalThis !== 'undefined' && globalThis.localStorage) {
  try {
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.startsWith('sb-') && key.endsWith('-auth-token')) {
        keysToRemove.push(key);
      }
    }
    keysToRemove.forEach(key => localStorage.removeItem(key));
  } catch (err) {
    console.error('Could not clear old supabase tokens', err);
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: false,
    autoRefreshToken: false,
  },
  global: {
    headers: {
      Authorization: `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
    }
  }
});
